### ISSUE TITLE
实用JDK1.8在windows上的一点小问题

### ISSUE THREAD

**Issue by guozhiqiang123** [yifei8/ARetrofit#11]
如果使用windows10+android studio开发，库中如果使用了jdk中的ClassLoader，则会出现rebuild的时候删除不了build文件夹中的一些生成的jar包。
这个是我在和AppInit这个库的作者一起调试发现的，该库作者使用GroovyClassLoader替换Java的ClassLoader解决了这个问题，现在我司项目还有这个问题，我现在在所有使用到的第三方库下都提了这个issures,如果库中没有使用，请自动忽略。。。
[AppInit的修复](https://github.com/Meituan-Dianping/AppInit/commit/95e23b32f318d4e34ba1775a199e64472d4d35f5)

这个问题只在windows上有出现，macOS上是没有的。并且我只测试了JDK1.8+windows10这一种情况，其他没有测试过。

**Comment by yifei8** [comment]
首先给楼主的行为点赞哈。
不过我这边也是Mac的环境，你说的这个windows环境如果出现了这个问题，我这个可能也会出现，回头我找个相同环境验证一下，如果楼主有兴趣验证并修复非常欢迎提个pr过来哦。

**Comment by guozhiqiang123** [comment]
哈哈  周末倒是可以帮你测试一下。不过应该不能帮你修复了，第一是能力还不够，还停留在用的阶段；第二是公司有个新的项目进来了，可能会比较忙。
