### ISSUE TITLE
作者您下一步的计划是什么？

### ISSUE THREAD

**Issue by guozhiqiang123** [yifei8/ARetrofit#8]
我司项目现在使用的是CC这个框架，这个框架有个最大的优点是可以实现代码隔离，缺点是不能很好管理所有跳转，开发人员多了就比较混乱，而作者的这个框架则很好的解决了这个问题。希望作者能吸取各大库的优点，解决更多的问题。当然希望作者不要误会我，我只是提个建议，完全没有义务去做这些事情。最后祝新年快乐！！！

**Comment by yifei8** [comment]
嗯，是的。关于这个问题我以前之前也有人问过我，我也给出了回答。

![image](https://user-images.githubusercontent.com/34327550/52162288-6e972200-270c-11e9-85c0-5ebbd97b86c3.png)

你提的这个问题，我会考虑的，回头打算写一篇这方面主题的文章，旨在帮助大家更好的对项目进行组件化

**Comment by guozhiqiang123** [comment]
嗯嗯，虽然我还没有重度使用过你这个框架，但是感觉应该非常不错。而且拦截器的功能可以再丰富点，感觉美团开源的MWRouter也挺厉害的，建议收纳其精华。谢谢作者的包容！拜年！


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
