### ISSUE TITLE
高阶用法的疑问

### ISSUE THREAD

**Issue by guozhiqiang123** [yifei8/ARetrofit#9]
高阶用法中的服务，可跨模块获取对象，请问如果这个对象需要异步生成之后才能获取到，这个有什么好的实现方式吗

**Comment by yifei8** [comment]
高阶用法中获取对象其实也就是一次对象的new操作，这个new操作一般是不可以异步的哈。我的理解你是不是仅仅是需要异步返回方法执行的结果。

**Comment by guozhiqiang123** [comment]
是的，我仅仅需要异步操作之后的结果。因为我需要new的这个对象，需要先网络请求一次更新它的某些属性，然后再返回
------------------

 





------------------ 原始邮件 ------------------
发件人: "yifei"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 晚上6:48
收件人: "yifei8/ARetrofit"<ARetrofit@noreply.github.com>;
抄送: "郭志强"<774550196@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yifei8/ARetrofit] 高阶用法的疑问 (#9)




高阶用法中获取对象其实也就是一次对象的new操作，这个new操作一般是不可以异步的哈。我的理解你是不是仅仅是需要异步返回方法执行的结果。

**Comment by yifei8** [comment]
举例：
//定义你需要的异步对象
public interface AsyncObject {

}

//IAsyncObjectProvider 异步对象的抽象工厂
public interface IAsyncObjectProvider  {
     public AsyncObject getAsyncObj();
}

@Route(path = "/login-module/ILoginProviderImpl")
public class IAsyncObjectProviderImpl implements IAsyncObjectProvider {

    @Override
    public AsyncObject getAsyncObj() {
        AsyncObject  obj ....
        //todo 耗时操作构造AsyncObject  
        return obj;
    }
}

**Comment by yifei8** [comment]
或者你这个“需要先网络请求一次更新它的某些属性”是网络请求到对象的构造的参数吧，这个跟你new一个对象是不同的操作啊，你可以先获取你需要的数据，再通过retrofit构造对象哈。

**Comment by guozhiqiang123** [comment]
![微信截图_20190430102823](https://user-images.githubusercontent.com/20378988/56938135-d0f89680-6b32-11e9-88f9-ddad0789c573.png)
![微信截图_20190430102901](https://user-images.githubusercontent.com/20378988/56938136-d524b400-6b32-11e9-85c2-1b5afea50fdc.png)
现在就是这么做的！！！

**Comment by yifei8** [comment]
赞

**Comment by xiaojinzi123** [comment]
怎么评论关了呀,这么经不起讨论吗？
抄的这么明显是当别人瞎了吗？

**Comment by guozhiqiang123** [comment]
> 怎么评论关了呀,这么经不起讨论吗？
> 抄的这么明显是当别人瞎了吗？

你是说抄你的这个库吗？（https://github.com/xiaojinzi123/Component）我虽然不是作者，但是你的那个库既然挂了开源协议，任何人都有权利使用和修改。你这算怎么回事？这点度量？而且就使用上来说，本库比你那个简洁高效多了！！！你有什么资格在我的issues下面瞎哔哔？

**Comment by xiaojinzi123** [comment]
> > 怎么评论关了呀,这么经不起讨论吗？
> > 抄的这么明显是当别人瞎了吗？
> 
> 你是说抄你的这个库吗？（[https://github.com/xiaojinzi123/Component）我虽然不是作者，但是你的那个库既然挂了开源协议，任何人都有权利使用和修改。你这算怎么回事？这点度量？而且就使用上来说，本库比你那个简洁高效多了！！！你有什么资格在我的issues下面瞎哔哔？](https://github.com/xiaojinzi123/Component%EF%BC%89%E6%88%91%E8%99%BD%E7%84%B6%E4%B8%8D%E6%98%AF%E4%BD%9C%E8%80%85%EF%BC%8C%E4%BD%86%E6%98%AF%E4%BD%A0%E7%9A%84%E9%82%A3%E4%B8%AA%E5%BA%93%E6%97%A2%E7%84%B6%E6%8C%82%E4%BA%86%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE%EF%BC%8C%E4%BB%BB%E4%BD%95%E4%BA%BA%E9%83%BD%E6%9C%89%E6%9D%83%E5%88%A9%E4%BD%BF%E7%94%A8%E5%92%8C%E4%BF%AE%E6%94%B9%E3%80%82%E4%BD%A0%E8%BF%99%E7%AE%97%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F%E8%BF%99%E7%82%B9%E5%BA%A6%E9%87%8F%EF%BC%9F%E8%80%8C%E4%B8%94%E5%B0%B1%E4%BD%BF%E7%94%A8%E4%B8%8A%E6%9D%A5%E8%AF%B4%EF%BC%8C%E6%9C%AC%E5%BA%93%E6%AF%94%E4%BD%A0%E9%82%A3%E4%B8%AA%E7%AE%80%E6%B4%81%E9%AB%98%E6%95%88%E5%A4%9A%E4%BA%86%EF%BC%81%EF%BC%81%EF%BC%81%E4%BD%A0%E6%9C%89%E4%BB%80%E4%B9%88%E8%B5%84%E6%A0%BC%E5%9C%A8%E6%88%91%E7%9A%84issues%E4%B8%8B%E9%9D%A2%E7%9E%8E%E5%93%94%E5%93%94%EF%BC%9F)

怎么可能抄我的库,抄谁的作者心里没有点逼数吗？
你们这一唱一和看的我想笑

**Comment by guozhiqiang123** [comment]
> > > 怎么评论关了呀,这么经不起讨论吗？
> > > 抄的这么明显是当别人瞎了吗？
> > 
> > 
> > 你是说抄你的这个库吗？（[https://github.com/xiaojinzi123/Component）我虽然不是作者，但是你的那个库既然挂了开源协议，任何人都有权利使用和修改。你这算怎么回事？这点度量？而且就使用上来说，本库比你那个简洁高效多了！！！你有什么资格在我的issues下面瞎哔哔？](https://github.com/xiaojinzi123/Component%EF%BC%89%E6%88%91%E8%99%BD%E7%84%B6%E4%B8%8D%E6%98%AF%E4%BD%9C%E8%80%85%EF%BC%8C%E4%BD%86%E6%98%AF%E4%BD%A0%E7%9A%84%E9%82%A3%E4%B8%AA%E5%BA%93%E6%97%A2%E7%84%B6%E6%8C%82%E4%BA%86%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE%EF%BC%8C%E4%BB%BB%E4%BD%95%E4%BA%BA%E9%83%BD%E6%9C%89%E6%9D%83%E5%88%A9%E4%BD%BF%E7%94%A8%E5%92%8C%E4%BF%AE%E6%94%B9%E3%80%82%E4%BD%A0%E8%BF%99%E7%AE%97%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F%E8%BF%99%E7%82%B9%E5%BA%A6%E9%87%8F%EF%BC%9F%E8%80%8C%E4%B8%94%E5%B0%B1%E4%BD%BF%E7%94%A8%E4%B8%8A%E6%9D%A5%E8%AF%B4%EF%BC%8C%E6%9C%AC%E5%BA%93%E6%AF%94%E4%BD%A0%E9%82%A3%E4%B8%AA%E7%AE%80%E6%B4%81%E9%AB%98%E6%95%88%E5%A4%9A%E4%BA%86%EF%BC%81%EF%BC%81%EF%BC%81%E4%BD%A0%E6%9C%89%E4%BB%80%E4%B9%88%E8%B5%84%E6%A0%BC%E5%9C%A8%E6%88%91%E7%9A%84issues%E4%B8%8B%E9%9D%A2%E7%9E%8E%E5%93%94%E5%93%94%EF%BC%9F)
> 
> 怎么可能抄我的库,抄谁的作者心里没有点逼数吗？
> 你们这一唱一和看的我想笑

我也不认识作者 我也只是该库的使用者，既然你觉得他抄你的，请另开issues讨论，不要在我的issues下面瞎搞，留我一个美好的周末，谢谢！！！

**Comment by xiaojinzi123** [comment]
> > > > 怎么评论关了呀,这么经不起讨论吗？
> > > > 抄的这么明显是当别人瞎了吗？
> > > 
> > > 
> > > 你是说抄你的这个库吗？（[https://github.com/xiaojinzi123/Component）我虽然不是作者，但是你的那个库既然挂了开源协议，任何人都有权利使用和修改。你这算怎么回事？这点度量？而且就使用上来说，本库比你那个简洁高效多了！！！你有什么资格在我的issues下面瞎哔哔？](https://github.com/xiaojinzi123/Component%EF%BC%89%E6%88%91%E8%99%BD%E7%84%B6%E4%B8%8D%E6%98%AF%E4%BD%9C%E8%80%85%EF%BC%8C%E4%BD%86%E6%98%AF%E4%BD%A0%E7%9A%84%E9%82%A3%E4%B8%AA%E5%BA%93%E6%97%A2%E7%84%B6%E6%8C%82%E4%BA%86%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE%EF%BC%8C%E4%BB%BB%E4%BD%95%E4%BA%BA%E9%83%BD%E6%9C%89%E6%9D%83%E5%88%A9%E4%BD%BF%E7%94%A8%E5%92%8C%E4%BF%AE%E6%94%B9%E3%80%82%E4%BD%A0%E8%BF%99%E7%AE%97%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F%E8%BF%99%E7%82%B9%E5%BA%A6%E9%87%8F%EF%BC%9F%E8%80%8C%E4%B8%94%E5%B0%B1%E4%BD%BF%E7%94%A8%E4%B8%8A%E6%9D%A5%E8%AF%B4%EF%BC%8C%E6%9C%AC%E5%BA%93%E6%AF%94%E4%BD%A0%E9%82%A3%E4%B8%AA%E7%AE%80%E6%B4%81%E9%AB%98%E6%95%88%E5%A4%9A%E4%BA%86%EF%BC%81%EF%BC%81%EF%BC%81%E4%BD%A0%E6%9C%89%E4%BB%80%E4%B9%88%E8%B5%84%E6%A0%BC%E5%9C%A8%E6%88%91%E7%9A%84issues%E4%B8%8B%E9%9D%A2%E7%9E%8E%E5%93%94%E5%93%94%EF%BC%9F)
> > 
> > 
> > 怎么可能抄我的库,抄谁的作者心里没有点逼数吗？
> > 你们这一唱一和看的我想笑
> 
> 我也不认识作者 我也只是该库的使用者，既然你觉得他抄你的，请另开issues讨论，不要在我的issues下面瞎搞，留我一个美好的周末，谢谢！！！

你都说我瞎哔哔了,那我为什么不能讨论,是不敢讨论吗？再说了没叫你回复啊.不懂可以不说话,谢谢

**Comment by guozhiqiang123** [comment]
> > > > > 怎么评论关了呀,这么经不起讨论吗？
> > > > > 抄的这么明显是当别人瞎了吗？
> > > > 
> > > > 
> > > > 你是说抄你的这个库吗？（[https://github.com/xiaojinzi123/Component）我虽然不是作者，但是你的那个库既然挂了开源协议，任何人都有权利使用和修改。你这算怎么回事？这点度量？而且就使用上来说，本库比你那个简洁高效多了！！！你有什么资格在我的issues下面瞎哔哔？](https://github.com/xiaojinzi123/Component%EF%BC%89%E6%88%91%E8%99%BD%E7%84%B6%E4%B8%8D%E6%98%AF%E4%BD%9C%E8%80%85%EF%BC%8C%E4%BD%86%E6%98%AF%E4%BD%A0%E7%9A%84%E9%82%A3%E4%B8%AA%E5%BA%93%E6%97%A2%E7%84%B6%E6%8C%82%E4%BA%86%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE%EF%BC%8C%E4%BB%BB%E4%BD%95%E4%BA%BA%E9%83%BD%E6%9C%89%E6%9D%83%E5%88%A9%E4%BD%BF%E7%94%A8%E5%92%8C%E4%BF%AE%E6%94%B9%E3%80%82%E4%BD%A0%E8%BF%99%E7%AE%97%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F%E8%BF%99%E7%82%B9%E5%BA%A6%E9%87%8F%EF%BC%9F%E8%80%8C%E4%B8%94%E5%B0%B1%E4%BD%BF%E7%94%A8%E4%B8%8A%E6%9D%A5%E8%AF%B4%EF%BC%8C%E6%9C%AC%E5%BA%93%E6%AF%94%E4%BD%A0%E9%82%A3%E4%B8%AA%E7%AE%80%E6%B4%81%E9%AB%98%E6%95%88%E5%A4%9A%E4%BA%86%EF%BC%81%EF%BC%81%EF%BC%81%E4%BD%A0%E6%9C%89%E4%BB%80%E4%B9%88%E8%B5%84%E6%A0%BC%E5%9C%A8%E6%88%91%E7%9A%84issues%E4%B8%8B%E9%9D%A2%E7%9E%8E%E5%93%94%E5%93%94%EF%BC%9F)
> > > 
> > > 
> > > 怎么可能抄我的库,抄谁的作者心里没有点逼数吗？
> > > 你们这一唱一和看的我想笑
> > 
> > 
> > 我也不认识作者 我也只是该库的使用者，既然你觉得他抄你的，请另开issues讨论，不要在我的issues下面瞎搞，留我一个美好的周末，谢谢！！！
> 
> 你都说我瞎哔哔了,那我为什么不能讨论,是不敢讨论吗？再说了没叫你回复啊.不懂可以不说话,谢谢

我说你这个人有毛病吧？我的GitHub是和邮箱关联的，不知道你在这讨论，会发邮件到我的邮箱吗？我周末就听你在这叽叽歪歪了？

**Comment by xiaojinzi123** [comment]
> > > > > > 怎么评论关了呀,这么经不起讨论吗？
> > > > > > 抄的这么明显是当别人瞎了吗？
> > > > > 
> > > > > 
> > > > > 你是说抄你的这个库吗？（[https://github.com/xiaojinzi123/Component）我虽然不是作者，但是你的那个库既然挂了开源协议，任何人都有权利使用和修改。你这算怎么回事？这点度量？而且就使用上来说，本库比你那个简洁高效多了！！！你有什么资格在我的issues下面瞎哔哔？](https://github.com/xiaojinzi123/Component%EF%BC%89%E6%88%91%E8%99%BD%E7%84%B6%E4%B8%8D%E6%98%AF%E4%BD%9C%E8%80%85%EF%BC%8C%E4%BD%86%E6%98%AF%E4%BD%A0%E7%9A%84%E9%82%A3%E4%B8%AA%E5%BA%93%E6%97%A2%E7%84%B6%E6%8C%82%E4%BA%86%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE%EF%BC%8C%E4%BB%BB%E4%BD%95%E4%BA%BA%E9%83%BD%E6%9C%89%E6%9D%83%E5%88%A9%E4%BD%BF%E7%94%A8%E5%92%8C%E4%BF%AE%E6%94%B9%E3%80%82%E4%BD%A0%E8%BF%99%E7%AE%97%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F%E8%BF%99%E7%82%B9%E5%BA%A6%E9%87%8F%EF%BC%9F%E8%80%8C%E4%B8%94%E5%B0%B1%E4%BD%BF%E7%94%A8%E4%B8%8A%E6%9D%A5%E8%AF%B4%EF%BC%8C%E6%9C%AC%E5%BA%93%E6%AF%94%E4%BD%A0%E9%82%A3%E4%B8%AA%E7%AE%80%E6%B4%81%E9%AB%98%E6%95%88%E5%A4%9A%E4%BA%86%EF%BC%81%EF%BC%81%EF%BC%81%E4%BD%A0%E6%9C%89%E4%BB%80%E4%B9%88%E8%B5%84%E6%A0%BC%E5%9C%A8%E6%88%91%E7%9A%84issues%E4%B8%8B%E9%9D%A2%E7%9E%8E%E5%93%94%E5%93%94%EF%BC%9F)
> > > > 
> > > > 
> > > > 怎么可能抄我的库,抄谁的作者心里没有点逼数吗？
> > > > 你们这一唱一和看的我想笑
> > > 
> > > 
> > > 我也不认识作者 我也只是该库的使用者，既然你觉得他抄你的，请另开issues讨论，不要在我的issues下面瞎搞，留我一个美好的周末，谢谢！！！
> > 
> > 
> > 你都说我瞎哔哔了,那我为什么不能讨论,是不敢讨论吗？再说了没叫你回复啊.不懂可以不说话,谢谢
> 
> 我说你这个人有毛病吧？我的GitHub是和邮箱关联的，不知道你在这讨论，会发邮件到我的邮箱吗？我周末就听你在这叽叽歪歪了？

我说了你可以闭嘴,这样子就没人说话了

**Comment by yifei8** [comment]
从时间上就说不过去，没点开源精神，喜欢在别人那边瞎逼逼，我关了这哥们之前的一个issue。这low货显然上来趁热度的，就是为了推广他那个这个垃圾库。各位此issue的读者，请坚决抵制此类low货写的东西，维护开源社区。

**Comment by xiaojinzi123** [comment]
> 从时间上就说不过去，没点开源精神，喜欢在别人那边瞎逼逼，我关了这哥们之前的一个issue。这low货显然上来趁热度的，就是为了推广他那个这个垃圾库。各位此issue的读者，请坚决抵制此类low货写的东西，维护开源社区。

简直就是笑死我了,趁热度需要靠你这几个star 的抄袭库？哥们你真的是都笑我了,一年的笑点都被你承包了.
你要真有技术你怎么不解决抄袭过来的时候一些问题.正儿八经的问题 issue 你关掉了还说别人.还有脸说开源精神？笑死我了
